### ISSUE TITLE
Request: Folder navigation & vignette

### ISSUE THREAD

**Issue by Mermouy** [mitsukarenai/PHPmyLMB-XT#3]
It would be great if someday, you could add the folder navigation, like making folder's title a link then we could browse medias per folder (in a vignette-style?)?
BTW is it the right place for that kind of question?

Ce serait chouette de pouvoir naviguer dans les dossier en cliquant sur leur nom? Et parcourir (ce serait encore mieux) en vue par vignette?
Je ne sais pas trop si c'est le bon endroit pour une telle question..?

**Comment by mitsukarenai** [comment]
Voir avec @benpro pour implémentation dans PHPmyLMB :)
